import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Omar Elnagdy Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider>
            {children} 
            <footer className="footer">
              © 2024 Omar Elnagdy
              <p className="power">Powered by NextJS</p>
            </footer>
        </TransitionProvider>
      </body>
    </html>
  );
}
